# Site settings
title: Mashudi Blog
tagline : 'Blog, Linux, Open Source, Tutorial, Desktop Art'

#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.


#author
url: "http://mashudicastol.github.io" # the base hostname & protocol for your site
twitter_username: MashudiCastol
github_username:  MashudiCastol

# Build settings
markdown: kramdown
