# Site settings
title: Mashudi Blog
header-img: img/home-bg.jpg
description: "All my notes about code experience"
baseurl: ""
url: "http://mashudisudonym.github.io"
email: muhamadmashudiardiwinata@gmail.com
twitter_username: MashudiSudonym
github_username:  MashudiSudonym
facebook_username:  muhamadmashudiardiwinata
linkedin_username: mashudi
google_tracking_id: UA-45573590-2
google_ad_client: ca-pub-7828759142515533

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
