# Site settings
title: Mashudi Blog
header-img: img/home-bg.jpg
email: muhamadmashudiardiwinata@gmail.com
description: "Blog catatan kuliah, oprek linux, dan aplikasi Free Open Source Software (FOSS)"
baseurl: ""
url: "http://mashudisudonym.github.io"
twitter_username: MashudiCastol
github_username:  MashudiSudonym
facebook_username:  muhamadmashudiardiwinata

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
